name: Setup Server

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show config
        run: |
          echo "SOFTWARE=Spigot"
          echo "VERSION=1.21.8"
          grep -E '^(START|VERSION|SOFTWARE)=' iraqi/.env || true
